from enum import Enum

class State(Enum):
  OFF = 1
  ON = 2
  DISCONNECTED = 3
  UNKNOWN = 4

deviceList = [{'topic': "/i3/inside/lights/001/", 'ledNum': 6, 'itemState': State.UNKNOWN},
{'topic': "/i3/inside/lights/002/", 'ledNum': 8, 'itemState': State.UNKNOWN},
{'topic': "/i3/inside/lights/003/", 'ledNum': 9, 'itemState': State.UNKNOWN},
{'topic': "/i3/inside/lights/004/", 'ledNum': 10, 'itemState': State.UNKNOWN},
{'topic': "/i3/inside/lights/005/", 'ledNum': 5, 'itemState': State.UNKNOWN},
{'topic': "/i3/inside/lights/006/", 'ledNum': 20, 'itemState': State.UNKNOWN},
{'topic': "/i3/inside/lights/007/", 'ledNum': 19, 'itemState': State.UNKNOWN},
{'topic': "/i3/inside/lights/008/", 'ledNum': 18, 'itemState': State.UNKNOWN},
{'topic': "/i3/inside/lights/009/", 'ledNum': 16, 'itemState': State.UNKNOWN},
{'topic': "/i3/inside/lights/010/", 'ledNum': 23, 'itemState': State.UNKNOWN},
{'topic': "/i3/inside/lights/011/", 'ledNum': 24, 'itemState': State.UNKNOWN},
{'topic': "/i3/inside/lights/012/", 'ledNum': 25, 'itemState': State.UNKNOWN},
{'topic': "/i3/inside/lights/013/", 'ledNum': 26, 'itemState': State.UNKNOWN},
{'topic': "/i3/inside/lights/014/", 'ledNum': 27, 'itemState': State.UNKNOWN},
{'topic': "/i3/inside/lights/015/", 'ledNum': 46, 'itemState': State.UNKNOWN},
{'topic': "/i3/inside/lights/016/", 'ledNum': 38, 'itemState': State.UNKNOWN},
{'topic': "/i3/inside/lights/017/", 'ledNum': 35, 'itemState': State.UNKNOWN},
{'topic': "/i3/inside/lights/018/", 'ledNum': 34, 'itemState': State.UNKNOWN},
{'topic': "/i3/inside/lights/019/", 'ledNum': 31, 'itemState': State.UNKNOWN},
{'topic': "/i3/inside/lights/020/", 'ledNum': 47, 'itemState': State.UNKNOWN},
{'topic': "/i3/inside/lights/021/", 'ledNum': 42, 'itemState': State.UNKNOWN},
{'topic': "/i3/inside/lights/022/", 'ledNum': 40, 'itemState': State.UNKNOWN},
{'topic': "/i3/inside/lights/023/", 'ledNum': 37, 'itemState': State.UNKNOWN},
{'topic': "/i3/inside/lights/024/", 'ledNum': 36, 'itemState': State.UNKNOWN},
{'topic': "/i3/inside/lights/025/", 'ledNum': 32, 'itemState': State.UNKNOWN},
{'topic': "/i3/inside/lights/026/", 'ledNum': 33, 'itemState': State.UNKNOWN},
{'topic': "/i3/inside/lights/027/", 'ledNum': 48, 'itemState': State.UNKNOWN},
{'topic': "/i3/inside/lights/028/", 'ledNum': 7, 'itemState': State.UNKNOWN},
{'topic': "/i3/inside/lights/029/", 'ledNum': 11, 'itemState': State.UNKNOWN},
{'topic': "/i3/inside/lights/030/", 'ledNum': 12, 'itemState': State.UNKNOWN},
{'topic': "/i3/inside/lights/031/", 'ledNum': 14, 'itemState': State.UNKNOWN},
{'topic': "/i3/inside/lights/032/", 'ledNum': 13, 'itemState': State.UNKNOWN},
{'topic': "/i3/inside/lights/033/", 'ledNum': 30, 'itemState': State.UNKNOWN},
{'topic': "/i3/inside/lights/034/", 'ledNum': 29, 'itemState': State.UNKNOWN},
{'topic': "/i3/inside/lights/035/", 'ledNum': 28, 'itemState': State.UNKNOWN},
{'topic': "/i3/inside/lights/036/", 'ledNum': 41, 'itemState': State.UNKNOWN},
{'topic': "/i3/inside/lights/037/", 'ledNum': 44, 'itemState': State.UNKNOWN},
{'topic': "/i3/commons/lights/snappleVending/", 'ledNum': 22, 'itemState': State.UNKNOWN},
{'topic': "/i3/inside/commons/bathroom-vent-fan/", 'ledNum': 50, 'itemState': State.UNKNOWN},
{'topic': "/i3/inside/commons/east-ceiling-fans/", 'ledNum': 17, 'itemState': State.UNKNOWN},
{'topic': "/i3/inside/commons/east-ceiling-fans/", 'ledNum': 21, 'itemState': State.UNKNOWN},
{'topic': "/i3/inside/fablab/vent/", 'ledNum': 39, 'itemState': State.UNKNOWN},
{'topic': "/i3/inside/office-bathroom/light/", 'ledNum': 49, 'itemState': State.UNKNOWN},
{'topic': "/i3/laserZone/ceilingFan/", 'ledNum': 43, 'itemState': State.UNKNOWN},
{'topic': "/i3/laserZone/ventFan/", 'ledNum': 45, 'itemState': State.UNKNOWN},
{'topic': "/i3/machineShop/fans/ceilingFan/", 'ledNum': 15, 'itemState': State.UNKNOWN}]